// Generated by CoffeeScript 1.4.0
var Histogram;

Histogram = (function() {

  function Histogram(image) {
    var area, colors, d, h, height, i, margin, maxY, svg, width, x, xAxis, xScale, y, yAxis, yScale, _i, _len, _ref;
    this.image = image;
    this.hist = (function() {
      var _i, _len, _ref, _results;
      _ref = get_channels(this.image);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        d = _ref[_i];
        _results.push(histogram(d.data, [0, 255], 255));
      }
      return _results;
    }).call(this);
    margin = {
      top: 20,
      right: 20,
      bottom: 30,
      left: 50
    };
    width = 600;
    height = 300;
    xScale = d3.scale.linear().range([0, width]);
    yScale = d3.scale.linear().range([height, 0]);
    xAxis = d3.svg.axis().scale(xScale).orient("bottom");
    yAxis = d3.svg.axis().scale(yScale).orient("left");
    maxY = 10000;
    xScale.domain([0, 255]);
    yScale.domain([0, maxY]);
    area = d3.svg.area().x(function(d) {
      return xScale(d[0]);
    }).y0(height).y1(function(d) {
      return yScale(d[1]);
    });
    d3.select("#hist").selectAll("svg").remove();
    svg = d3.select("#hist").append("svg").attr("width", width + margin.left + margin.right).attr("height", height + margin.top + margin.bottom).append("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");
    svg.append("g").attr("class", "x axis").attr("transform", "translate(0," + height + ")").call(xAxis);
    svg.append("g").attr("class", "y axis").call(yAxis);
    colors = ["red", "green", "blue"];
    _ref = this.hist;
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      h = _ref[i];
      d = (function() {
        var _j, _len1, _results;
        _results = [];
        for (x = _j = 0, _len1 = h.length; _j < _len1; x = ++_j) {
          y = h[x];
          _results.push([x, y]);
        }
        return _results;
      })();
      svg.append("path").datum(d).attr("class", "hist " + colors[i]).attr("d", area);
    }
  }

  return Histogram;

})();
